### ISSUE TITLE
TTP Model Refinements

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctim#198]
These model refinements are needed to support the addition of CAPEC data to AMP Global Intel, and to develop mappings between the TG indicators and TTP data from Mitre and elsewhere.

- [x] [#186 Make attack pattern, malware, and tool sourcable.](https://github.com/threatgrid/ctim/issues/186)
- [x] [#190 Add abstraction level to Attack Patterns](https://github.com/threatgrid/ctim/issues/190)
- [x] [#196 Add Weakness entity](https://github.com/threatgrid/ctim/issues/196)
- [x] [#195 Add Vulnerability entity](https://github.com/threatgrid/ctim/issues/195)
- [x] [#197 Malware abstraction level](https://github.com/threatgrid/ctim/issues/197)
- [x] [#194 Remove ExploitTarget](https://github.com/threatgrid/ctim/issues/194)

- [x] CTIA Support for the above model changes
- [x] Data Migration in INT, TEST, and PROD
